### ISSUE TITLE
Can't open apps

### ISSUE THREAD

**Issue by emb3625** [leftyfl1p/Springround#7]
Device type: iPod touch 6
iOS version: iOS 9.0.2

**Issue:** I cannot open any apps from the Springround view. Happens every time I open the view. I can navigate pages, folders, and the Search screen just fine. Strangely, I can open apps from the Search screen, just not from the home pages themselves.

**Comment by leftyfl1p** [comment]
This is basically a more descriptive version of #2.

**Comment by emb3625** [comment]
Technically yes, but the icons do function in the other ways. I can trigger a fake 3D Touch (with HOPP'N), tap and hold to get the wiggly mode, and move them around. By clicking on an app it'll close the view, but it won't open the app selected, which is the issue.

**Comment by leftyfl1p** [comment]
Build 15 should fix this.
