### ISSUE TITLE
The blurriness does not cover the whole iPad screen.

### ISSUE THREAD

**Issue by Shedoara** [leftyfl1p/Springround#8]
You can still interact with that area as well. I have Harbor installed so that's why my dock is like that. Here's some pictures of it. https://imgur.com/a/Yss8k

EDIT: whoops forgot to put what I have. 
Version: iOS 8.4
iPad Air

**Comment by leftyfl1p** [comment]
Hopefully build 28 fixed it. I know it's fixed for iPhones but I don't know for iPad.

**Comment by leftyfl1p** [comment]
@Shedoara can you confirm or deny that this is fixed?

**Comment by leftyfl1p** [comment]
Closing since nobody is reporting that this problem still exists.
