### ISSUE TITLE
Low frame rate with the Settings app open

### ISSUE THREAD

**Issue by Shedoara** [leftyfl1p/Springround#9]
Can't seem to reproduce it in anything else, but the Settings app. The frame rate is very low when swiping between springboard pages and folders while in it.

iOS 8.4/iPad Air

**Comment by leftyfl1p** [comment]
Very strange considering there's nothing going on any different in the settings app than any other app on my end. Do you have any UI tweaks like eclipse enabled?

**Comment by Shedoara** [comment]
Nope, I do not. Only thing I had that changes the settings at all is Preferences Orginizer, which I disabled to make sure it wasn't that, but it didn't help any.
